config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :entries
  resources :comments
  
  # get 'home/index'

  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
  validates :entry, presence: true
  validates :body, presence: true
  validates :commenter, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
  validates :subheader, presence:  true
  validates :body, presence: true
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@comment = Comment.new(comment_params)
  	respond_to do |format|
  		if @comment.save
      	format.html { redirect_to @comment.entry, notice: 'Comentario creado exitosamente.' }
      end
    end
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.entry, notice: 'Comentario eliminado exitosamente.' }
    end
  end

  private
  	def comment_params
      params.require(:comment).permit(:commenter, :body, :entry_id)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :edit, :create, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @comment = Comment.new
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Noticia creada exitosamente.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Noticia editada exitosamente.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Noticia eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def check_admin
      redirect_to root_path unless current_user.admin? 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :subheader, :body, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_form.html.erb
<div class="container">
	<%= form_for @comment do |f| %>
		<div class="container">
			<h3>Comentar</h3>
		  <div class="row justify-content-center">
		    <div class="col-lg-12 col-md-12">
					<h5 class="mt-4 mb-3">Nombre:</h5>
					<div class="card border-info mb-3">
		      	<div class="card-header text-info">
			  			<%= f.text_field :commenter, class: "form-control no-border", required: true %>
		      	</div>
		      </div>
				</div>

				<div class="col-lg-12 col-md-12">
					<h5 class="mt-4 mb-3">Comentario:</h5>
					<div class="card border-info mb-3">
		      	<div class="card-header text-info">
			  			<%= f.text_area :body, class: "form-control no-border", required: true %>
		      	</div>
		      </div>
				</div>
			</div>
		</div>

		<div class="row justify-content-center">
			<div class="col-lg-6 col-md-6">
			  <%= f.hidden_field :entry_id, value: @entry.id %>
			  <%= f.submit "Publicar comentario", class: "btn btn-info btn-block" %>
			</div>
		</div>
	<% end %>
</div>

app/views/entries/_form.html.erb
<div class="container">
  <%= form_with(model: entry, local: true) do |form| %>
    <% if entry.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
        <ul>
        <% entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row justify-content-center">
      <div class="col-lg-12 col-md-12">
        <h5 class="mt-4 mb-3">Título:</h5>
        <div class="card border-info mb-3">
          <div class="card-header text-info">
            <%= form.text_field :title, class: "form-control no-border", required: true %>
          </div>
        </div>
      </div>

      <div class="col-lg-12 col-md-12">
        <h5 class="mt-4 mb-3">Bajada:</h5>
        <div class="card border-info mb-3">
          <div class="card-header text-info">
            <%= form.text_field :subheader, class: "form-control no-border", required: true %>
          </div>
        </div>
      </div>

      <div class="col-lg-12 col-md-12">
        <h5 class="mt-4 mb-3">Cuerpo:</h5>
        <div class="card border-info mb-3">
          <div class="card-header text-info">
            <%= form.text_area :body, class: "form-control no-border", required: true %>
          </div>
        </div>
      </div>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="actions">
      <div class="row justify-content-center">
        <div class="col-md-6 col-lg-6">
          <%= form.submit 'Publicar', class: "btn btn-info btn-block" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/entries/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-12 col-md-12">
      <h3 class="mt-4 mb-3">Editar Noticia</h3>
    </div>
  </div>
</div>

<%= render 'form', entry: @entry %>

<br>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-4 col-lg-3">
			<%= link_to 'Atrás', entries_path, class: "btn btn-block btn-outline-info" %>
		</div>
		<div class="col-md-4 col-lg-3">
			<%= link_to 'Ver', @entry, class: "btn btn-block btn-outline-info" %> 
		</div>
	</div>
</div>
<br>

app/views/entries/index.html.erb
<h1>Noticias</h1>
<table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Bajada</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th>Comentarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.subheader %></td>
        <td><%= entry.body.truncate(500, separator: ' ') %></td>
        <td><%= entry.created_at.to_s(:short) %></td>
        <td><%= entry.comments.count %></td>
        <td><%= link_to 'Ver', entry, class: "btn btn-success" %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Editar', edit_entry_path(entry), class: "btn btn-outline-secondary" %></td>
          <td><%= link_to 'Eliminar', entry, method: :delete, data: { confirm: 'Estás seguro/a?' }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row justify-content-center digg_pagination">
  <%= will_paginate @entries, page_links: false, previous_label: 'Página anterior', next_label: 'Página siguiente' %>
</div>

<br>
<% if current_user.admin? %>
  <div class="row justify-content-center">
    <div class="col-lg-3 col-md-4">
      <%= link_to 'Nueva Noticia', new_entry_path, class: "btn btn-info btn-block" %>
    </div>
  </div>
<% end %>

app/views/entries/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-12 col-md-12">
      <h3 class="mt-4 mb-3">Nueva Noticia</h3>
    </div>
  </div>
</div>
<%= render 'form', entry: @entry %>

<br>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-4 col-lg-3">
			<%= link_to 'Atrás', entries_path, class: "btn btn-block btn-outline-info" %>
		</div>
	</div>
</div>
<br>

app/views/entries/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-12 col-md-12">
			<h3 class="mt-4 mb-3">Título:</h3>
			<div class="card border-info mb-3">
      	<div class="card-header text-info">
  				<%= @entry.title %>
      	</div>
      </div>
		</div>
	</div>

	<div class="row justify-content-center">
    <div class="col-lg-12 col-md-12">
			<h3 class="mt-4 mb-3">Bajada:</h3>
			<div class="card border-info mb-3">
      	<div class="card-header text-info">
  				<%= @entry.subheader %>
      	</div>
      </div>
		</div>
	</div>

	<div class="row justify-content-center">
    <div class="col-lg-12 col-md-12">
			<h3 class="mt-4 mb-3">Cuerpo:</h3>
			<div class="card border-info mb-3">
      	<div class="card-header text-info">
  				<%= @entry.body %>
      	</div>
      </div>
		</div>
	</div>

	<div class="row justify-content-center">
    <div class="col-lg-12 col-md-12">
			<h3 class="mt-4 mb-3">Fecha:</h3>
			<div class="card border-info mb-3">
      	<div class="card-header text-info">
  				<%= @entry.created_at.to_s(:short) %>
      	</div>
      </div>
		</div>
	</div>

	<h3 class="mt-4 mb-3">Comentarios:</h3>
	<div class="row justify-content-center">
		<% @entry.comments.each do |comment| %>
	    <div class="col-lg-10 col-md-10">
				<div class="card border-info mb-3">
	      	<div class="card-header text-info">
	  				Nombre: <%= comment.commenter %>
	      	</div>
	      	<div class="card-header text-info">
	  				Comentario: <%= comment.body %>
	      	</div>
	      </div>
			</div>
			<% if current_user.admin? %>
				<div class="col-lg-2 col-md-2">
		    	<%= link_to 'Eliminar', comment, method: :delete, data: { confirm: 'Estás seguro/a?' }, class: "btn btn-info btn-warning btn-block" %>
				</div>
		  <% end %>
		<% end %>
	</div>

	<br>
	<%= render partial: 'comments/form' %>

</div>
<br>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-4 col-lg-3">
			<%= link_to 'Atrás', entries_path, class: "btn btn-block btn-outline-info" %>
		</div>
		<div class="col-md-4 col-lg-3">
			<% if current_user.admin? %>
				<%= link_to 'Editar noticia', edit_entry_path(@entry), class: "btn btn-block btn-outline-secondary" %>
			<% end %>
		</div>
	</div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>

    <p class="navbar-text pull-right">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
          <% if user_signed_in? %>
            Ingresado/a como <strong><%= current_user.email %></strong>.
            <%= link_to (current_user.admin? ? "Administrar noticias" : "Ver noticias"), entries_path, :class => 'navbar-link' %> |          
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Ingresar", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </div>
    </div>
    </p>

    <%= yield %>
  </body>
</html>